/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"




*/


class Solution {
public char findTheDifference(String s, String t) {
char[] ch1 = s.toCharArray();
char[] ch2 = t.toCharArray();
Arrays.sort(ch1);
Arrays.sort(ch2);
for (int i = 0; i < ch1.length; i++) {
if (ch1[i] != ch2[i]) {
return ch2[i];
}
}
return ch2[ch2.length-1];
}
}
